name: mineral_cache
description: Cache for the Mineral framework.
version: 1.0.0-dev.2
repository: https://github.com/mineral-dart/cache

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  mineral:
    git:
      url: https://github.com/mineral-dart/core.git
      ref: develop
  redis: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
